name: acceptance_tester
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.3
  json_annotation: ^4.9.0
  file_picker: ^8.0.0
  animate_do: ^3.3.4
  intl: ^0.19.0
  url_launcher: ^6.3.0
  dotted_border: ^2.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Google Symbol.png
